### ISSUE TITLE
Permission denied when app is started as described on release page

### ISSUE THREAD

**Issue by ewoks** [ns130291/MonkeyRemote#2]
If user starts the app as described by developer:
`java -jar MonkeyRemote-0.1.jar "D:\SDK\platform-tools" 1.0`

app will crash with Permission Denied Exception.

 Crash log:

> CreateProcess error=5, Zugriff verweigert
> Exception in thread "main" java.lang.IllegalArgumentException: java.io.IOExcepti
> on: Cannot run program "D:\SDK\platform-tools": CreateProces
> s error=5, Zugriff verweigert
>         at com.android.ddmlib.AndroidDebugBridge.<init>(AndroidDebugBridge.java:
> 567)
>         at com.android.ddmlib.AndroidDebugBridge.createBridge(AndroidDebugBridge
> .java:324)
>         at com.android.chimpchat.adb.AdbBackend.<init>(AdbBackend.java:69)
>         at com.android.chimpchat.ChimpChat.createBackendByName(ChimpChat.java:78
> )
>         at com.android.chimpchat.ChimpChat.getInstance(ChimpChat.java:51)
>         at de.nsvb.monkeyremote.MonkeyRemote.main(MonkeyRemote.java:91)
> Caused by: java.io.IOException: Cannot run program "D:\SDK\platform-tools": CreateProcess error=5, Zugriff verweigert
>         at java.lang.ProcessBuilder.start(Unknown Source)
>         at com.android.ddmlib.AndroidDebugBridge$1.run(AndroidDebugBridge.java:6
> 25)
>         at java.lang.Thread.run(Unknown Source)
> Caused by: java.io.IOException: CreateProcess error=5, Zugriff verweigert
>         at java.lang.ProcessImpl.create(Native Method)
>         at java.lang.ProcessImpl.<init>(Unknown Source)
>         at java.lang.ProcessImpl.start(Unknown Source)
>         ... 3 more

**Comment by ns130291** [comment]
I think you should add `\adb.exe` to your path, otherwise it won't work. I will add a check to warn the user.
