### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by tuxayo** [ns130291/MonkeyRemote#6]
Hi, actually I'm taking a long time to fix my phone and I'm using your tool a lot, thanks again!

I would like to try to implement an automatic reconnection as I'm having a lot of times input not working when starting a "session" and I have to start a new one, often multiple times.
And it also happens in the middle of a session if the phone is locked.

So I hope to be able to explore that but we need the project to have a libre/open source license. Because by default, now MonkeyRemote is "All rights reserved"

I have a preference for the [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.txt) as it's copyleft **but** not strong copyleft, so from what I understand, no compatibility issues with other licenses, so it can be part of other projects without issue.

If you prefer another license, fine, no issues for me as long as it's libre/open source ^^

**Comment by ns130291** [comment]
I've added the GPLv3 license
